// Local clothing image library with AI-generated illustrations
import { ImageSourcePropType } from 'react-native';

// Import actual PNG images generated by FLUX Schnell
import tshirt from '@/assets/clothing/tshirt.png';
import shirt from '@/assets/clothing/shirt.png';
import sweater from '@/assets/clothing/sweater.png';
import hoodie from '@/assets/clothing/hoodie.png';
import pants from '@/assets/clothing/pants.png';
import shorts from '@/assets/clothing/shorts.png';
import jeans from '@/assets/clothing/jeans.png';
import lightJacket from '@/assets/clothing/light-jacket.png';
import warmCoat from '@/assets/clothing/warm-coat.png';
import rainJacket from '@/assets/clothing/rain-jacket.png';
import sunHat from '@/assets/clothing/sun-hat.png';
import warmHat from '@/assets/clothing/warm-hat.png';
import sunglasses from '@/assets/clothing/sunglasses.png';
import gloves from '@/assets/clothing/gloves.png';
import boots from '@/assets/clothing/boots.png';
import rainBoots from '@/assets/clothing/rain-boots.png';

export interface ClothingImageMap {
  [key: string]: ImageSourcePropType;
}

// Mapping of clothing items to local image assets
const clothingImages: ClothingImageMap = {
  // Tops
  'tshirt': tshirt,
  't-shirt': tshirt,
  'shirt': shirt,
  'long-sleeve': shirt,
  'long-sleeved': shirt,
  'sweater': sweater,
  'sweatshirt': sweater,
  'hoodie': hoodie,

  // Bottoms
  'pants': pants,
  'jeans': jeans,
  'shorts': shorts,
  'leggings': pants,

  // Outerwear
  'jacket': lightJacket,
  'light-jacket': lightJacket,
  'windbreaker': lightJacket,
  'coat': warmCoat,
  'warm-coat': warmCoat,
  'winter-coat': warmCoat,
  'rain-jacket': rainJacket,
  'raincoat': rainJacket,

  // Accessories - Head
  'hat': warmHat,
  'sun-hat': sunHat,
  'beanie': warmHat,
  'warm-hat': warmHat,
  'winter-hat': warmHat,
  'sunglasses': sunglasses,

  // Accessories - Hands/Feet
  'gloves': gloves,
  'mittens': gloves,
  'boots': boots,
  'rain-boots': rainBoots,
  'shoes': boots,
  'sneakers': boots,
  'socks': gloves,

  // Other - using available images as fallbacks
  'scarf': warmHat,
  'umbrella': rainJacket,
  'vest': lightJacket,
  'dress': tshirt,
  'cardigan': sweater,
};

export class ClothingImageLibrary {
  /**
   * Get the local image for a clothing item
   * Returns actual PNG image import for instant display
   */
  static getImage(itemName: string): ImageSourcePropType | null {
    const normalizedName = itemName.toLowerCase().trim();

    // Direct match
    if (clothingImages[normalizedName]) {
      return clothingImages[normalizedName];
    }

    // Partial match - find if the key is contained in the item name
    for (const [key, image] of Object.entries(clothingImages)) {
      if (normalizedName.includes(key) || key.includes(normalizedName)) {
        return image;
      }
    }

    return null;
  }

  /**
   * Get images for multiple clothing items
   * Returns a Map of item names to their corresponding images
   */
  static getImages(items: string[]): Map<string, ImageSourcePropType> {
    const imageMap = new Map<string, ImageSourcePropType>();

    for (const item of items) {
      const image = this.getImage(item);
      if (image) {
        imageMap.set(item, image);
      }
    }

    return imageMap;
  }

  /**
   * Check if an image exists for a clothing item
   */
  static hasImage(itemName: string): boolean {
    return this.getImage(itemName) !== null;
  }

  /**
   * Get all available clothing items
   */
  static getAvailableItems(): string[] {
    return Object.keys(clothingImages);
  }
}
